/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveViewRouteImport } from './routes/live-view'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGetAnnotatedLiveFrameRouteImport } from './routes/api/get-annotated-live-frame'
import { Route as ApiAuditLogsOverviewRouteImport } from './routes/api/audit-logs/overview'
import { Route as ApiAuditLogsEventsRouteImport } from './routes/api/audit-logs/events'

const LiveViewRoute = LiveViewRouteImport.update({
  id: '/live-view',
  path: '/live-view',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetAnnotatedLiveFrameRoute =
  ApiGetAnnotatedLiveFrameRouteImport.update({
    id: '/api/get-annotated-live-frame',
    path: '/api/get-annotated-live-frame',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuditLogsOverviewRoute = ApiAuditLogsOverviewRouteImport.update({
  id: '/api/audit-logs/overview',
  path: '/api/audit-logs/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsEventsRoute = ApiAuditLogsEventsRouteImport.update({
  id: '/api/audit-logs/events',
  path: '/api/audit-logs/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/live-view': typeof LiveViewRoute
  '/api/get-annotated-live-frame': typeof ApiGetAnnotatedLiveFrameRoute
  '/api/audit-logs/events': typeof ApiAuditLogsEventsRoute
  '/api/audit-logs/overview': typeof ApiAuditLogsOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/live-view': typeof LiveViewRoute
  '/api/get-annotated-live-frame': typeof ApiGetAnnotatedLiveFrameRoute
  '/api/audit-logs/events': typeof ApiAuditLogsEventsRoute
  '/api/audit-logs/overview': typeof ApiAuditLogsOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/live-view': typeof LiveViewRoute
  '/api/get-annotated-live-frame': typeof ApiGetAnnotatedLiveFrameRoute
  '/api/audit-logs/events': typeof ApiAuditLogsEventsRoute
  '/api/audit-logs/overview': typeof ApiAuditLogsOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/live-view'
    | '/api/get-annotated-live-frame'
    | '/api/audit-logs/events'
    | '/api/audit-logs/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/live-view'
    | '/api/get-annotated-live-frame'
    | '/api/audit-logs/events'
    | '/api/audit-logs/overview'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/live-view'
    | '/api/get-annotated-live-frame'
    | '/api/audit-logs/events'
    | '/api/audit-logs/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  LiveViewRoute: typeof LiveViewRoute
  ApiGetAnnotatedLiveFrameRoute: typeof ApiGetAnnotatedLiveFrameRoute
  ApiAuditLogsEventsRoute: typeof ApiAuditLogsEventsRoute
  ApiAuditLogsOverviewRoute: typeof ApiAuditLogsOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live-view': {
      id: '/live-view'
      path: '/live-view'
      fullPath: '/live-view'
      preLoaderRoute: typeof LiveViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-annotated-live-frame': {
      id: '/api/get-annotated-live-frame'
      path: '/api/get-annotated-live-frame'
      fullPath: '/api/get-annotated-live-frame'
      preLoaderRoute: typeof ApiGetAnnotatedLiveFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs/overview': {
      id: '/api/audit-logs/overview'
      path: '/api/audit-logs/overview'
      fullPath: '/api/audit-logs/overview'
      preLoaderRoute: typeof ApiAuditLogsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs/events': {
      id: '/api/audit-logs/events'
      path: '/api/audit-logs/events'
      fullPath: '/api/audit-logs/events'
      preLoaderRoute: typeof ApiAuditLogsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  LiveViewRoute: LiveViewRoute,
  ApiGetAnnotatedLiveFrameRoute: ApiGetAnnotatedLiveFrameRoute,
  ApiAuditLogsEventsRoute: ApiAuditLogsEventsRoute,
  ApiAuditLogsOverviewRoute: ApiAuditLogsOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
